RULES_DB = {
    "IND_AS_1": {
        "version": "1.0.0",
        "description": "Compliance rules for Indian Accounting Standard (Ind AS) 1: Presentation of Financial Statements.",
        "rules": [
            {"rule_id": "INDAS1-01", "description": "Present a complete set of financial statements including Balance Sheet, Statement of Profit and Loss, Statement of Changes in Equity, Statement of Cash Flows, and Notes.", "mapped_paragraphs": "10", "type": "Structural"},
            {"rule_id": "INDAS1-02", "description": "Present a single Statement of Profit and Loss with two sections: Profit or Loss first, followed by Other Comprehensive Income.", "mapped_paragraphs": "10A", "type": "Structural"},
            {"rule_id": "INDAS1-03", "description": "Include an explicit and unreserved statement of compliance with Ind AS in the notes.", "mapped_paragraphs": "16", "type": "Disclosure"},
            {"rule_id": "INDAS1-04", "description": "Prepare financial statements on a going concern basis unless management intends to liquidate or cease trading; disclose material uncertainties if they exist.", "mapped_paragraphs": "25", "type": "Disclosure"},
            {"rule_id": "INDAS1-05", "description": "Prepare financial statements (except Cash Flow) using the accrual basis of accounting.", "mapped_paragraphs": "27", "type": "Structural"},
            {"rule_id": "INDAS1-06", "description": "Present separately each material class of similar items; present dissimilar items separately unless immaterial.", "mapped_paragraphs": "29", "type": "Structural"},
            {"rule_id": "INDAS1-07", "description": "Do not offset assets and liabilities or income and expenses unless required or permitted by an Ind AS.", "mapped_paragraphs": "32", "type": "Numerical"},
            {"rule_id": "INDAS1-08", "description": "Present a complete set of financial statements at least annually; disclose reasons if reporting period changes.", "mapped_paragraphs": "36", "type": "Structural"},
            {"rule_id": "INDAS1-09", "description": "Present comparative information for the preceding period for all amounts reported in the current period.", "mapped_paragraphs": "38", "type": "Numerical"},
            {"rule_id": "INDAS1-10", "description": "Present a third balance sheet (at the beginning of the preceding period) if applying an accounting policy retrospectively or making a retrospective restatement that has a material effect.", "mapped_paragraphs": "40A", "type": "Structural"},
            {"rule_id": "INDAS1-11", "description": "Clearly identify the financial statements, reporting currency, and level of rounding.", "mapped_paragraphs": "49–51", "type": "Disclosure"},
            {"rule_id": "INDAS1-12", "description": "Include minimum line items in the Balance Sheet (e.g., PPE, Intangible Assets, Financial Assets, Inventories, Trade Receivables, Cash, Trade Payables, Provisions).", "mapped_paragraphs": "54", "type": "Structural"},
            {"rule_id": "INDAS1-13", "description": "Present Current and Non-current assets and liabilities as separate classifications (unless liquidity presentation is more reliable).", "mapped_paragraphs": "60", "type": "Structural"},
            {"rule_id": "INDAS1-14", "description": "Classify an asset as current if realized in the normal operating cycle, held for trading, or realized within 12 months.", "mapped_paragraphs": "66", "type": "Structural"},
            {"rule_id": "INDAS1-15", "description": "Classify a liability as current if settled in normal operating cycle, held for trading, due within 12 months, or if there is no unconditional right to defer settlement for 12 months.", "mapped_paragraphs": "69", "type": "Structural"},
            {"rule_id": "INDAS1-16", "description": "Classify liabilities based on rights at the end of the reporting period; breaches rectified after the period do not convert current liabilities to non-current.", "mapped_paragraphs": "72B, 74–76ZA", "type": "Structural"},
            {"rule_id": "INDAS1-17", "description": "Disclose share capital details: authorized, issued, par value, and reconciliation of shares at beginning/end of period.", "mapped_paragraphs": "79", "type": "Numerical"},
            {"rule_id": "INDAS1-18", "description": "Present Total Comprehensive Income, allocating amounts attributable to owners of the parent and non-controlling interests.", "mapped_paragraphs": "81A–81B", "type": "Numerical"},
            {"rule_id": "INDAS1-19", "description": "Include minimum line items in Profit or Loss section (Revenue, Finance costs, Tax expense, etc.).", "mapped_paragraphs": "82", "type": "Numerical"},
            {"rule_id": "INDAS1-20", "description": "Group Other Comprehensive Income (OCI) items into those that will not be reclassified to profit or loss and those that will be.", "mapped_paragraphs": "82A", "type": "Structural"},
            {"rule_id": "INDAS1-21", "description": "Do not present any items of income or expense as 'extraordinary items'.", "mapped_paragraphs": "87", "type": "Structural"},
            {"rule_id": "INDAS1-22", "description": "Present analysis of expenses recognized in profit or loss using the 'nature of expense' method.", "mapped_paragraphs": "99", "type": "Structural"},
            {"rule_id": "INDAS1-23", "description": "Present a Statement of Changes in Equity showing total comprehensive income, retrospective adjustments, and reconciliation of carrying amounts.", "mapped_paragraphs": "106", "type": "Numerical"},
            {"rule_id": "INDAS1-24", "description": "Disclose dividends recognized as distributions and related amount per share.", "mapped_paragraphs": "107", "type": "Disclosure"},
            {"rule_id": "INDAS1-25", "description": "Present notes in a systematic manner and cross-reference them to the main financial statements.", "mapped_paragraphs": "113", "type": "Structural"},
            {"rule_id": "INDAS1-26", "description": "Disclose material accounting policy information.", "mapped_paragraphs": "117", "type": "Disclosure"},
            {"rule_id": "INDAS1-27", "description": "Disclose judgements (apart from estimations) that management has made that have the most significant effect on recognized amounts.", "mapped_paragraphs": "122", "type": "Disclosure"},
            {"rule_id": "INDAS1-28", "description": "Disclose assumptions and major sources of estimation uncertainty that have a significant risk of resulting in material adjustments.", "mapped_paragraphs": "125", "type": "Disclosure"},
            {"rule_id": "INDAS1-29", "description": "Disclose qualitative and quantitative information about objectives, policies, and processes for managing capital.", "mapped_paragraphs": "134–135", "type": "Disclosure"},
            {"rule_id": "INDAS1-30", "description": "Disclose proposed dividends declared after the reporting period but before approval of financial statements.", "mapped_paragraphs": "137", "type": "Disclosure"},
            {"rule_id": "INDAS1-31", "description": "Disclose the domicile and legal form of the entity, its country of incorporation, registered office address, nature of operations, and name of the parent entity.", "mapped_paragraphs": "138", "type": "Disclosure"}
        ]
    },
    "IND_AS_7": {
        "version": "1.0.0",
        "description": "Compliance rules for Indian Accounting Standard (Ind AS) 7: Statement of Cash Flows.",
        "rules": [
            {"rule_id": "INDAS7-01", "description": "Prepare a statement of cash flows and present it as an integral part of the financial statements for each period presented.", "mapped_paragraphs": "1", "type": "Structural"},
            {"rule_id": "INDAS7-02", "description": "Classify cash flows during the period into operating, investing, and financing activities.", "mapped_paragraphs": "10", "type": "Structural"},
            {"rule_id": "INDAS7-03", "description": "Report cash flows from operating activities using either the direct method or the indirect method.", "mapped_paragraphs": "18", "type": "Structural"},
            {"rule_id": "INDAS7-04", "description": "Report separately major classes of gross cash receipts and gross cash payments for investing and financing activities (unless netting criteria are met).", "mapped_paragraphs": "21", "type": "Structural"},
            {"rule_id": "INDAS7-05", "description": "Report on a net basis only for: (a) customers' behalf, (b) items with quick turnover/large amount/short maturity, or (c) specific financial institution activities.", "mapped_paragraphs": "22–24", "type": "Structural"},
            {"rule_id": "INDAS7-06", "description": "Record foreign currency cash flows at the exchange rate at the date of the cash flow (or a weighted average approximation).", "mapped_paragraphs": "25–27", "type": "Numerical"},
            {"rule_id": "INDAS7-07", "description": "Exclude unrealized foreign exchange gains and losses from cash flows; present them separately to reconcile opening and closing cash balances.", "mapped_paragraphs": "28", "type": "Numerical"},
            {"rule_id": "INDAS7-08", "description": "For non-financial entities: Classify interest paid as Financing, interest and dividends received as Investing, and dividends paid as Financing.", "mapped_paragraphs": "31", "type": "Structural"},
            {"rule_id": "INDAS7-09", "description": "For financial institutions: Classify interest paid and interest and dividends received as Operating activities.", "mapped_paragraphs": "31", "type": "Structural"},
            {"rule_id": "INDAS7-10", "description": "Disclose total interest paid, whether expensed in profit or loss or capitalized.", "mapped_paragraphs": "32", "type": "Disclosure"},
            {"rule_id": "INDAS7-11", "description": "Disclose cash flows from income taxes separately and classify as operating unless specifically identified with investing or financing.", "mapped_paragraphs": "35", "type": "Structural"},
            {"rule_id": "INDAS7-12", "description": "Restrict reporting of cash flows from equity/cost method investments (associates/subsidiaries) to actual cash flows between investor and investee.", "mapped_paragraphs": "37", "type": "Numerical"},
            {"rule_id": "INDAS7-13", "description": "Present aggregate cash flows arising from obtaining or losing control of subsidiaries separately and classify as investing activities.", "mapped_paragraphs": "39", "type": "Structural"},
            {"rule_id": "INDAS7-14", "description": "Disclose details of obtaining/losing control: consideration paid/received, portion in cash, and amount of cash/assets/liabilities in the subsidiary.", "mapped_paragraphs": "40", "type": "Disclosure"},
            {"rule_id": "INDAS7-15", "description": "Classify cash flows from changes in ownership interests in a subsidiary that do not result in a loss of control as financing activities.", "mapped_paragraphs": "42A", "type": "Structural"},
            {"rule_id": "INDAS7-16", "description": "Exclude non-cash investing and financing transactions (e.g., debt to equity conversion) from the statement of cash flows; disclose elsewhere.", "mapped_paragraphs": "43", "type": "Disclosure"},
            {"rule_id": "INDAS7-17", "description": "Disclose changes in liabilities arising from financing activities, distinguishing between cash changes and non-cash changes (e.g., FX, fair value).", "mapped_paragraphs": "44A–44B", "type": "Disclosure"},
            {"rule_id": "INDAS7-18", "description": "Disclose aggregate information about supplier finance arrangements: terms, carrying amounts, and payment due date ranges.", "mapped_paragraphs": "44H", "type": "Disclosure"},
            {"rule_id": "INDAS7-19", "description": "Disclose components of cash and cash equivalents and present a reconciliation to the amounts reported in the balance sheet.", "mapped_paragraphs": "45", "type": "Disclosure"},
            {"rule_id": "INDAS7-20", "description": "Disclose the policy adopted in determining the composition of cash and cash equivalents.", "mapped_paragraphs": "46", "type": "Disclosure"},
            {"rule_id": "INDAS7-21", "description": "Disclose significant cash and cash equivalent balances held by the entity that are not available for use by the group (with management commentary).", "mapped_paragraphs": "48", "type": "Disclosure"}
        ]
    },
    "IND_AS_115": {
        "version": "1.0.0",
        "description": "Compliance rules for Indian Accounting Standard (Ind AS) 115: Revenue from Contracts with Customers.",
        "rules": [
            {"rule_id": "INDAS115-01", "description": "Recognize revenue to depict the transfer of promised goods or services to customers in an amount reflecting the consideration expected.", "mapped_paragraphs": "2", "type": "Structural"},
            {"rule_id": "INDAS115-02", "description": "Account for a contract only when all 5 criteria are met: approval, identified rights, identified payment terms, commercial substance, and probable collection.", "mapped_paragraphs": "9", "type": "Structural"},
            {"rule_id": "INDAS115-03", "description": "Combine contracts entered into at/near the same time with the same customer if negotiated as a package, linked price, or single performance obligation.", "mapped_paragraphs": "17", "type": "Structural"},
            {"rule_id": "INDAS115-04", "description": "Identify distinct goods or services (or a series of distinct goods/services) as separate performance obligations.", "mapped_paragraphs": "22", "type": "Structural"},
            {"rule_id": "INDAS115-05", "description": "Recognize revenue when (or as) the entity satisfies a performance obligation by transferring control of the asset to the customer.", "mapped_paragraphs": "31", "type": "Structural"},
            {"rule_id": "INDAS115-06", "description": "Recognize revenue over time if: customer consumes benefits simultaneously, controls asset as created, or asset has no alternative use and entity has right to payment.", "mapped_paragraphs": "35", "type": "Structural"},
            {"rule_id": "INDAS115-07", "description": "Determine the transaction price including fixed consideration, variable consideration, financing components, non-cash consideration, and amounts payable to customers.", "mapped_paragraphs": "47–48", "type": "Numerical"},
            {"rule_id": "INDAS115-08", "description": "Treat penalties inherent in the determination of transaction price as variable consideration; otherwise, treat per the substance of the contract.", "mapped_paragraphs": "51AA", "type": "Numerical"},
            {"rule_id": "INDAS115-09", "description": "Estimate variable consideration using 'expected value' or 'most likely amount' and constrain estimates to prevent significant revenue reversal.", "mapped_paragraphs": "53, 56", "type": "Numerical"},
            {"rule_id": "INDAS115-10", "description": "Adjust transaction price for significant financing components unless the period between transfer and payment is one year or less (practical expedient).", "mapped_paragraphs": "60–63", "type": "Numerical"},
            {"rule_id": "INDAS115-11", "description": "Allocate the transaction price to each performance obligation based on relative stand-alone selling prices.", "mapped_paragraphs": "74", "type": "Numerical"},
            {"rule_id": "INDAS115-12", "description": "Recognize incremental costs of obtaining a contract as an asset if recoverable; expense if amortization period is one year or less.", "mapped_paragraphs": "91, 94", "type": "Structural"},
            {"rule_id": "INDAS115-13", "description": "Recognize costs to fulfill a contract as an asset only if they relate directly to the contract, generate/enhance resources, and are recoverable.", "mapped_paragraphs": "95", "type": "Structural"},
            {"rule_id": "INDAS115-14", "description": "Present unconditional rights to consideration as 'Receivables' and conditional rights as 'Contract Assets'.", "mapped_paragraphs": "105–108", "type": "Structural"},
            {"rule_id": "INDAS115-15", "description": "Present separately the amount of excise duty included in the revenue recognized in the statement of profit and loss.", "mapped_paragraphs": "109AA", "type": "Disclosure"},
            {"rule_id": "INDAS115-16", "description": "Disaggregate revenue into categories that depict how economic factors affect the nature, amount, timing, and uncertainty of revenue.", "mapped_paragraphs": "114", "type": "Disclosure"},
            {"rule_id": "INDAS115-17", "description": "Disclose opening and closing balances of receivables, contract assets, and contract liabilities.", "mapped_paragraphs": "116", "type": "Disclosure"},
            {"rule_id": "INDAS115-18", "description": "Disclose the aggregate transaction price allocated to remaining (unsatisfied) performance obligations and when revenue is expected to be recognized.", "mapped_paragraphs": "120", "type": "Disclosure"},
            {"rule_id": "INDAS115-19", "description": "Disclose significant judgements made regarding timing of satisfaction (over time vs. point in time) and determination of transaction price.", "mapped_paragraphs": "123", "type": "Disclosure"},
            {"rule_id": "INDAS115-20", "description": "Reconcile revenue recognized in profit and loss with the contracted price, showing separately adjustments for discounts, rebates, refunds, etc.", "mapped_paragraphs": "126AA", "type": "Disclosure"},
            {"rule_id": "INDAS115-21", "description": "For Service Concession Arrangements: The operator shall not recognize infrastructure as Property, Plant and Equipment.", "mapped_paragraphs": "App C, 11", "type": "Structural"},
            {"rule_id": "INDAS115-22", "description": "For Service Concession Arrangements: Recognize consideration as a Financial Asset (unconditional right to cash) or Intangible Asset (right to charge users).", "mapped_paragraphs": "App C, 16–17", "type": "Structural"}
        ]
    }
}